### PR TITLE
[WIP] Drop gulp and use peerDependencies and move to RC3 of @angular/core

### PR DESCRIPTION
**Pull request by kamilkisiela**
- [x] peerDependencies of `@angular/core`, `@angular/platform-browser`, `@angular/platform-browser-dynamic` and `angular2-meteor` (it was missing).
- [x] use `tsc` and npm scripts instead of gulp
- [x] update to latest (1.3) `typings` and use `globalDependencies` instead of `ambientDependencies` (deprecated)
- [x] update to Angular RC3 (RC1 `BROWSER_APP_DYNAMIC_PROVIDERS` since RC2  `BROWSER_APP_COMPILER_PROVIDERS`)
- [ ] do some testing with Socially

### CODE REVIEW

**Comment by kamilkisiela** [comment]
@barbatus [Every PR is free to be a WIP :notes: ](https://www.youtube.com/watch?v=_VEjHcFpfns)

I haven't finished testing so I don't know if it works :smiling_imp:

**Comment by barbatus** [comment]
@kamilkisiela (I just hurried a bit) BTW Why did you change dependencies to peerDependencies? I think NPM 3.x is a recommended version, which flattens packages.

**Comment by kamilkisiela** [comment]
I just hurried a bit too! :smile: 

There is a breaking change that hasn't been noted in angular's changelog:

`BROWSER_APP_DYNAMIC_PROVIDERS`  for RC1
`BROWSER_APP_COMPILER_PROVIDERS` since RC2.

@barbatus Am I looking correct at this? Is this what we need to use to bootstrap an app?

**Comment by barbatus** [comment]
Yes this is for the bootstrapping, but what does it say about dependencies vs peerDependencies?

**Comment by kamilkisiela** [comment]
@barbatus I'm not talking about dep vs peerDep. I'll change it.

I wanted to hear your point of view on that "breaking change" topic. I haven't dove into it yet, to check if there are any major changes or just the new name.

**Comment by barbatus** [comment]
@kamilkisiela yes you are right about `BROWSER_APP_COMPILER_PROVIDERS`, thanks )

**Pull request merged**
